// Code generated by MockGen. DO NOT EDIT.
// Source: Api.go

// Package testdata is a generated GoMock package.
package testdata

import (
	vo "bepaid-sdk/service/vo"
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApi is a mock of Api interface.
type MockApi struct {
	ctrl     *gomock.Controller
	recorder *MockApiMockRecorder
}

// MockApiMockRecorder is the mock recorder for MockApi.
type MockApiMockRecorder struct {
	mock *MockApi
}

// NewMockApi creates a new mock instance.
func NewMockApi(ctrl *gomock.Controller) *MockApi {
	mock := &MockApi{ctrl: ctrl}
	mock.recorder = &MockApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApi) EXPECT() *MockApiMockRecorder {
	return m.recorder
}

// Authorizations mocks base method.
func (m *MockApi) Authorizations(ctx context.Context, request *vo.AuthorizationRequest) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorizations", ctx, request)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorizations indicates an expected call of Authorizations.
func (mr *MockApiMockRecorder) Authorizations(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorizations", reflect.TypeOf((*MockApi)(nil).Authorizations), ctx, request)
}

// Captures mocks base method.
func (m *MockApi) Captures(ctx context.Context, capture *vo.CaptureRequest) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Captures", ctx, capture)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Captures indicates an expected call of Captures.
func (mr *MockApiMockRecorder) Captures(ctx, capture interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Captures", reflect.TypeOf((*MockApi)(nil).Captures), ctx, capture)
}
