// Code generated by MockGen. DO NOT EDIT.
// Source: service/contracts/service.go

// Package testdata is a generated GoMock package.
package testdata

import (
	vo "bepaid-sdk/service/vo"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApiService is a mock of ApiService interface.
type MockApiService struct {
	ctrl     *gomock.Controller
	recorder *MockApiServiceMockRecorder
}

// MockApiServiceMockRecorder is the mock recorder for MockApiService.
type MockApiServiceMockRecorder struct {
	mock *MockApiService
}

// NewMockApiService creates a new mock instance.
func NewMockApiService(ctrl *gomock.Controller) *MockApiService {
	mock := &MockApiService{ctrl: ctrl}
	mock.recorder = &MockApiServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiService) EXPECT() *MockApiServiceMockRecorder {
	return m.recorder
}

// Authorizations mocks base method.
func (m *MockApiService) Authorizations(ctx context.Context, authorizationRequest vo.AuthorizationRequest) (vo.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorizations", ctx, authorizationRequest)
	ret0, _ := ret[0].(vo.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorizations indicates an expected call of Authorizations.
func (mr *MockApiServiceMockRecorder) Authorizations(ctx, authorizationRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorizations", reflect.TypeOf((*MockApiService)(nil).Authorizations), ctx, authorizationRequest)
}

// Capture mocks base method.
func (m *MockApiService) Capture(ctx context.Context, captureRequest vo.CaptureRequest) (vo.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", ctx, captureRequest)
	ret0, _ := ret[0].(vo.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture.
func (mr *MockApiServiceMockRecorder) Capture(ctx, captureRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockApiService)(nil).Capture), ctx, captureRequest)
}
